In [1]:
import torch
import numpy as np

Example of a basic Tensor:

In [60]:
data = [[1, 2], [3, 4],[5,6],[8,9]]
x_data = torch.tensor(data)

In [6]:
print(x_data)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [8, 9]])


You can create and fill a tensor with random numbers:

In [9]:
size = (3,4)

In [94]:
random = torch.rand(size)
print(random)

tensor([[0.4291, 0.3399, 0.4652, 0.8522],
        [0.9181, 0.7763, 0.3119, 0.7246],
        [0.1773, 0.9135, 0.2582, 0.1633]])


How to view the characteristics of a tensor:

In [14]:
print(random.shape)
print(random.dtype)

torch.Size([3, 4])
torch.float32


In [16]:
onetensor = torch.ones(size)
print(onetensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


You can do arthrematic between tensors +,-,*,/

In [19]:
additiontensor = random + onetensor
print(additiontensor)

tensor([[1.2367, 1.8027, 1.7034, 1.7173],
        [1.5605, 1.8436, 1.0814, 1.9874],
        [1.7924, 1.1293, 1.8034, 1.6534]])


In [21]:
divisiontensor = onetensor / random
print(divisiontensor)

tensor([[ 4.2252,  1.2458,  1.4217,  1.3940],
        [ 1.7841,  1.1854, 12.2829,  1.0127],
        [ 1.2619,  7.7318,  1.2448,  1.5304]])


You can also look at individual scalars in a Tensor similar to a Numpy array and replace numbers in an tensor

In [96]:
indextensor = random
index = indextensor[2,1]
print(index)


tensor(0.9135)


In [98]:
indextensor[2,1] = 4.7
print(indextensor)

tensor([[0.4291, 0.3399, 0.4652, 0.8522],
        [0.9181, 0.7763, 0.3119, 0.7246],
        [0.1773, 4.7000, 0.2582, 0.1633]])
