Some Basic examples of Tensors in Pytorch

In [29]:
import torch
import numpy as np

Example of a basic Tensor:

In [33]:
data = [[1, 2], [3, 4],[5,6],[8,10]]
x_data = torch.tensor(data)

In [35]:
print(x_data)
print(x_data.shape)
print(x_data.dtype)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 8, 10]])
torch.Size([4, 2])
torch.int64


You can create and fill a tensor with random numbers:

In [37]:
size = (3,4)

In [39]:
random = torch.rand(size)
print(random)

tensor([[0.3583, 0.4989, 0.9984, 0.6779],
        [0.5855, 0.7061, 0.3161, 0.7417],
        [0.8184, 0.7163, 0.7482, 0.1745]])


How to view the characteristics of a tensor:

In [14]:
print(random.shape)
print(random.dtype)

torch.Size([3, 4])
torch.float32


In [41]:
onetensor = torch.ones(size)
print(onetensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


You can do arithmetic between tensors +,-,*,/

In [43]:
additiontensor = random + onetensor
print(additiontensor)

tensor([[1.3583, 1.4989, 1.9984, 1.6779],
        [1.5855, 1.7061, 1.3161, 1.7417],
        [1.8184, 1.7163, 1.7482, 1.1745]])


In [45]:
divisiontensor = onetensor / random
print(divisiontensor)

tensor([[2.7908, 2.0042, 1.0016, 1.4751],
        [1.7078, 1.4162, 3.1634, 1.3482],
        [1.2219, 1.3961, 1.3365, 5.7301]])


You can also look at individual scalars in a Tensor similar to a Numpy array and replace numbers in a tensor.

In [61]:
indextensor = random
index = indextensor[2,2]
print(index)


tensor(0.7482)


In [63]:
indextensor[2,1] = 4.7
print(indextensor)

tensor([[0.3583, 0.4989, 0.9984, 0.6779],
        [0.5855, 0.7061, 0.3161, 0.7417],
        [0.8184, 4.7000, 0.7482, 0.1745]])
